m_counters$drop()
m_counters$insert('{"_id":"authors", "seq":0}')
m_counters$insert('{"_id":"equipment", "seq":0}')
m_counters$insert('{"_id":"exps", "seq":0}')
m_counters$insert('{"_id":"subjects", "seq":0}')
m_counters$insert('{"_id":"blocks", "seq":0}')
m_counters$insert('{"_id":"trials", "seq":0}')
m_counters$insert('{"_id":"stims", "seq":0}')

m_authors$drop()
m_equipment$drop()
m_exp$drop()
m_subj$drop()
m_blocks$drop()
m_trials$drop()

m_stims$drop()
